# _config.yml

# ===== 사이트 URL 설정 (테스트 환경) =====
# 최종 배포 시에는 실제 도메인 주소로 변경
url: "https://hamnyk.github.io"
baseurl: "/test"

# ===== 사이트 정보 =====
title: 주식회사 워플로지
description: AI·온톨로지 지능형 워크플로 디자인 & 솔루션

# ===== 빌드 설정 =====
markdown: kramdown